# Random forest

In [94]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
import pandas as pd
from sklearn.metrics import r2_score

In [95]:
# this is the final version of the data set
property_data_2017_2022 = pd.read_csv('../data/raw/2017_2022_house_data_final.csv')
property_data_2023_2025 = pd.read_csv('../data/raw/2023_2025_house_data_final.csv')

In [96]:
property_data_2023_2025['car'] = property_data_2023_2025['car'].fillna(0)
property_data_2023_2025['bed'] = property_data_2023_2025['bed'].fillna(0)
property_data_2023_2025['bath'] = property_data_2023_2025['bath'].fillna(0)
property_data_2023_2025 = property_data_2023_2025[property_data_2023_2025['real_school_distance'] != 'school_distance_txt']
property_data_2023_2025 = property_data_2023_2025[property_data_2023_2025['real_school_duration'] != 'school_duration_txt']
property_data_2023_2025 = property_data_2023_2025[property_data_2023_2025['real_school_duration'] != 'duration_txt']
property_data_2023_2025 = property_data_2023_2025[property_data_2023_2025['real_station_distance'] != 'station_distance_txt']
property_data_2023_2025 = property_data_2023_2025[property_data_2023_2025['real_station_duration'] != 'station_duration_txt']
property_data_2023_2025 = property_data_2023_2025[property_data_2023_2025['real_station_duration'] != 'duration_txt']
property_data_2017_2022 = property_data_2017_2022[property_data_2017_2022['real_school_distance'] != 'school_distance_txt']
property_data_2017_2022 = property_data_2017_2022[property_data_2017_2022['real_school_duration'] != 'school_duration_txt']
property_data_2017_2022 = property_data_2017_2022[property_data_2017_2022['real_school_duration'] != 'duration_txt']
property_data_2017_2022 = property_data_2017_2022[property_data_2017_2022['real_station_distance'] != 'station_distance_txt']
property_data_2017_2022 = property_data_2017_2022[property_data_2017_2022['real_station_duration'] != 'station_duration_txt']
property_data_2017_2022 = property_data_2017_2022[property_data_2017_2022['real_station_duration'] != 'duration_txt']

In [97]:
property_data_2023_2025 = property_data_2023_2025.dropna()

In [98]:
X = property_data_2017_2022[['Population','real_station_distance','real_school_distance','car','Income','bed','bath','Hospital num']]
y = property_data_2017_2022['week_rent']

In [99]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)
regressor = RandomForestRegressor(n_estimators = 10,random_state = 0)
regressor.fit(X_train,y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

In [100]:
y_pred = regressor.predict(X_test)
y_pred

array([461. , 420. , 343. , ..., 447. , 329.5, 539.5])

In [104]:
r2_score(y_test,y_pred)

0.20161581399340933

In [ ]:
X_future = property_data_2023_2025[['Population','real_station_distance','real_school_distance','car','Income','bed','bath','Hospital num']]

In [ ]:
# predict the future renting fee
y_pred_future = regressor.predict(X_future)

In [ ]:
property_data_2023_2025['week_rent'] = y_pred_future

In [ ]:
property_data_2023_2025[property_data_2023_2025['year']==2023].groupby('closest_sa2').mean('week_rent')

,Unnamed: 0,year,postcode,bed,bath,car,Income,Population,real_school_distance,real_school_duration,real_station_distance,real_station_duration,week_rent,Hospital num
closest_sa2,,,,,,,,,,,,,,
Abbotsford,3868.5,2023.0,3067.000000,2.086957,1.391304,0.913043,81544.466667,10702.943793,0.863043,2.002174,1.295652,2.845652,513.785145,0.00000
Airport West,2934.5,2023.0,3042.000000,2.458333,1.291667,1.208333,75230.333333,8903.628239,70.779167,50.587500,6.962500,12.866667,418.083730,0.00000
Albert Park,8200.0,2023.0,3206.000000,2.225806,1.451613,0.516129,136184.000000,17757.337367,0.583871,1.361290,4.548387,8.516129,610.004032,0.00000
Alexandra,9754.5,2023.0,3712.750000,1.500000,1.000000,2.000000,51276.266667,6892.605984,2.375000,3.550000,96.350000,86.025000,384.300000,0.25000
Alfredton,8912.5,2023.0,3350.047619,3.500000,1.833333,2.023810,70289.200000,17329.283789,1.461905,2.823810,100.023810,74.502381,554.327381,0.97619
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Yarram,10529.0,2023.0,3971.000000,2.000000,2.000000,1.000000,68774.133333,5518.650707,7.300000,8.800000,163.100000,125.900000,407.500000,1.00000
Yarraville,1293.5,2023.0,3013.000000,2.500000,1.333333,1.125000,94355.066667,17391.074855,0.787500,1.808333,1.236111,2.570833,596.062731,0.00000
Yarrawonga,9780.0,2023.0,3730.000000,3.120000,1.640000,1.880000,57209.066667,8899.435002,59.552000,42.296000,250.668000,166.504000,616.553333,1.00000
Yarriambiack,9100.5,2023.0,3393.000000,2.250000,0.750000,1.250000,25631.333333,6335.776383,1.250000,2.500000,308.725000,213.525000,458.025000,0.50000
Yea,9757.5,2023.0,3717.000000,1.500000,0.500000,1.500000,54748.866667,4015.991539,6.350000,6.650000,56.450000,54.700000,3050.666667,1.00000

In [ ]:
property_data_2023_2025[property_data_2023_2025['year']==2024].groupby('closest_sa2').mean('week_rent')

,Unnamed: 0,year,postcode,bed,bath,car,Income,Population,real_school_distance,real_school_duration,real_station_distance,real_station_duration,week_rent,Hospital num
closest_sa2,,,,,,,,,,,,,,
Abbotsford,14526.5,2024.0,3067.000000,2.086957,1.391304,0.913043,83152.638095,10987.020074,0.863043,2.002174,1.295652,2.845652,514.904710,0.00000
Airport West,13592.5,2024.0,3042.000000,2.458333,1.291667,1.208333,77289.761905,9066.113460,70.779167,50.587500,6.962500,12.866667,442.235119,0.00000
Albert Park,18858.0,2024.0,3206.000000,2.225806,1.451613,0.516129,138784.000000,18004.743688,0.583871,1.361290,4.548387,8.516129,610.004032,0.00000
Alexandra,20412.5,2024.0,3712.750000,1.500000,1.000000,2.000000,52332.180952,6947.566013,2.375000,3.550000,96.350000,86.025000,376.675000,0.25000
Alfredton,19570.5,2024.0,3350.047619,3.500000,1.833333,2.023810,71850.457143,18035.230371,1.461905,2.823810,100.023810,74.502381,550.205159,0.97619
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Yarram,21187.0,2024.0,3971.000000,2.000000,2.000000,1.000000,70855.019048,5530.180592,7.300000,8.800000,163.100000,125.900000,390.250000,1.00000
Yarraville,11951.5,2024.0,3013.000000,2.500000,1.333333,1.125000,96937.295238,17743.666356,0.787500,1.808333,1.236111,2.570833,599.499421,0.00000
Yarrawonga,20438.0,2024.0,3730.000000,3.120000,1.640000,1.880000,58454.009524,9026.509334,59.552000,42.296000,250.668000,166.504000,607.649524,1.00000
Yarriambiack,19758.5,2024.0,3393.000000,2.250000,0.750000,1.250000,23612.761905,6274.369491,1.250000,2.500000,308.725000,213.525000,458.025000,0.50000
Yea,20415.5,2024.0,3717.000000,1.500000,0.500000,1.500000,55994.266667,4046.400489,6.350000,6.650000,56.450000,54.700000,3049.166667,1.00000

In [ ]:
property_data_2023_2025[property_data_2023_2025['year']==2025].groupby('closest_sa2').mean('week_rent')

,Unnamed: 0,year,postcode,bed,bath,car,Income,Population,real_school_distance,real_school_duration,real_station_distance,real_station_duration,week_rent,Hospital num
closest_sa2,,,,,,,,,,,,,,
Abbotsford,25184.5,2025.0,3067.000000,2.086957,1.391304,0.913043,84760.809524,11271.096356,0.863043,2.002174,1.295652,2.845652,522.921014,0.00000
Airport West,24250.5,2025.0,3042.000000,2.458333,1.291667,1.208333,79349.190476,9228.598682,70.779167,50.587500,6.962500,12.866667,439.250000,0.00000
Albert Park,29516.0,2025.0,3206.000000,2.225806,1.451613,0.516129,141384.000000,18252.150009,0.583871,1.361290,4.548387,8.516129,612.418011,0.00000
Alexandra,31070.5,2025.0,3712.750000,1.500000,1.000000,2.000000,53388.095238,7002.526041,2.375000,3.550000,96.350000,86.025000,380.800000,0.25000
Alfredton,30228.5,2025.0,3350.047619,3.500000,1.833333,2.023810,73411.714286,18741.176953,1.461905,2.823810,100.023810,74.502381,557.302381,0.97619
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Yarram,31845.0,2025.0,3971.000000,2.000000,2.000000,1.000000,72935.904762,5541.710478,7.300000,8.800000,163.100000,125.900000,391.000000,1.00000
Yarraville,22609.5,2025.0,3013.000000,2.500000,1.333333,1.125000,99519.523810,18096.257857,0.787500,1.808333,1.236111,2.570833,594.918750,0.00000
Yarrawonga,31096.0,2025.0,3730.000000,3.120000,1.640000,1.880000,59698.952381,9153.583665,59.552000,42.296000,250.668000,166.504000,603.109524,1.00000
Yarriambiack,30416.5,2025.0,3393.000000,2.250000,0.750000,1.250000,21594.190476,6212.962598,1.250000,2.500000,308.725000,213.525000,458.025000,0.50000
Yea,31073.5,2025.0,3717.000000,1.500000,0.500000,1.500000,57239.666667,4076.809439,6.350000,6.650000,56.450000,54.700000,3048.666667,1.00000

In [109]:
test = property_data_2023_2025[property_data_2023_2025['year']==2025].groupby('closest_sa2').mean('week_rent').reset_index()

In [110]:
#As for the large house so many demand of the house
test[test.closest_sa2 == 'Taylors Lakes']

,closest_sa2,Unnamed: 0,year,postcode,bed,bath,car,Income,Population,real_school_distance,real_school_duration,real_station_distance,real_station_duration,Hospital num
289,Taylors Lakes,24067.0,2025.0,3037.714286,3.571429,1.857143,2.428571,74879.47619,18164.08877,65.542857,45.242857,3.3,6.585714,0.142857

In [111]:
test[test.closest_sa2 == 'Wheelers Hill']

,closest_sa2,Unnamed: 0,year,postcode,bed,bath,car,Income,Population,real_school_distance,real_school_duration,real_station_distance,real_station_duration,Hospital num
322,Wheelers Hill,27640.0,2025.0,3150.0,3.842105,2.157895,2.0,78893.666667,21752.770952,0.826316,2.431579,5.078947,10.615789,2.0