# Random forest


# 2023-2025缺少邮编为3000的数据

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
import pandas as pd
from sklearn.metrics import r2_score

In [5]:
# this is the final version of the data set
property_data_2017_2022 = pd.read_csv('../data/raw/2017_2022_house_data_final.csv')
property_data_2023_2025 = pd.read_csv('../data/raw/2023_2025_house_data_final.csv')

In [6]:
property_data_2023_2025['car'] = property_data_2023_2025['car'].fillna(0)
property_data_2023_2025['bed'] = property_data_2023_2025['bed'].fillna(0)
property_data_2023_2025['bath'] = property_data_2023_2025['bath'].fillna(0)
property_data_2023_2025 = property_data_2023_2025[property_data_2023_2025['real_school_distance'] != 'school_distance_txt']
property_data_2023_2025 = property_data_2023_2025[property_data_2023_2025['real_school_duration'] != 'school_duration_txt']
property_data_2023_2025 = property_data_2023_2025[property_data_2023_2025['real_school_duration'] != 'duration_txt']
property_data_2023_2025 = property_data_2023_2025[property_data_2023_2025['real_station_distance'] != 'station_distance_txt']
property_data_2023_2025 = property_data_2023_2025[property_data_2023_2025['real_station_duration'] != 'station_duration_txt']
property_data_2023_2025 = property_data_2023_2025[property_data_2023_2025['real_station_duration'] != 'duration_txt']

property_data_2017_2022 = property_data_2017_2022[property_data_2017_2022['real_school_distance'] != 'school_distance_txt']
property_data_2017_2022 = property_data_2017_2022[property_data_2017_2022['real_school_duration'] != 'school_duration_txt']
property_data_2017_2022 = property_data_2017_2022[property_data_2017_2022['real_school_duration'] != 'duration_txt']
property_data_2017_2022 = property_data_2017_2022[property_data_2017_2022['real_station_distance'] != 'station_distance_txt']
property_data_2017_2022 = property_data_2017_2022[property_data_2017_2022['real_station_duration'] != 'station_duration_txt']
property_data_2017_2022 = property_data_2017_2022[property_data_2017_2022['real_station_duration'] != 'duration_txt']

In [7]:
property_data_2023_2025 = property_data_2023_2025.dropna()

In [8]:
X = property_data_2017_2022[['Population','real_station_duration','real_school_duration','real_station_distance','real_school_distance','car','Income','bed','bath','Hospital num']]
y = property_data_2017_2022['week_rent']

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)
regressor = RandomForestRegressor(n_estimators = 10,random_state = 0)
regressor.fit(X_train,y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

In [10]:
y_pred = regressor.predict(X_test)
y_pred

array([275.5, 332. , 366.5, ..., 412. , 416. , 406. ])

In [11]:
X_future = property_data_2023_2025[['Population','real_station_duration','real_school_duration','real_station_distance','real_school_distance','car','Income','bed','bath','Hospital num']]

In [12]:
# predict the future renting fee
y_pred_future = regressor.predict(X_future)

In [13]:
property_data_2023_2025['week_rent'] = y_pred_future

In [14]:
property_data_2023_2025.head()

,Unnamed: 0,name,property_type,year,coordinates,postcode,sa2_coor,closest_sa2,bed,bath,car,Income,Population,real_school_distance,real_school_duration,real_station_distance,real_station_duration,week_rent,Hospital num
0,0,101/25-33 Wills Street Melbourne VIC 3000,Apartment / Unit / Flat,2023,"[-37.8107757, 144.9569269]",3000,[xcoord 144.962765\nycoord -37.813377\nN...,Melbourne,1.0,1.0,0.0,129324.0,47744.2,0.7,1.7,0.5,1.2,417.619048,4.0
1,1,2905B/11 Rose Lane Melbourne VIC 3000,Apartment / Unit / Flat,2023,"[-37.815446, 144.9541165]",3000,[xcoord 144.962765\nycoord -37.813377\nN...,Melbourne,2.0,1.0,1.0,129324.0,47744.2,0.9,2.3,1.5,3.0,565.250000,4.0
2,2,1901/368 St Kilda Road Melbourne VIC 3000,Apartment / Unit / Flat,2023,"[-37.8318086, 144.9710272]",3000,[xcoord 144.962765\nycoord -37.813377\nN...,Melbourne,3.0,2.0,2.0,129324.0,47744.2,2.0,3.6,1.6,2.4,979.400000,4.0
3,3,1211/200 Spencer Street Melbourne VIC 3000,Apartment / Unit / Flat,2023,"[-37.816228, 144.9532465]",3000,[xcoord 144.962765\nycoord -37.813377\nN...,Melbourne,1.0,1.0,1.0,129324.0,47744.2,0.8,1.8,1.4,2.4,597.583333,4.0
4,4,1008/380 Little Lonsdale Street Melbourne VIC ...,Apartment / Unit / Flat,2023,"[-37.8121026, 144.9581291]",3000,[xcoord 144.962765\nycoord -37.813377\nN...,Melbourne,1.0,1.0,0.0,129324.0,47744.2,0.7,1.8,0.5,1.3,374.948810,4.0

In [15]:
property_data_2023_2025.groupby('closest_sa2').mean('week_rent')

,Unnamed: 0,year,postcode,bed,bath,car,Income,Population,real_school_distance,real_school_duration,real_station_distance,real_station_duration,week_rent,Hospital num
closest_sa2,,,,,,,,,,,,,,
Abbotsford,14526.5,2024.0,3067.000000,2.086957,1.391304,0.913043,83152.638095,10987.020074,0.863043,2.002174,1.295652,2.845652,508.627778,0.00000
Airport West,13592.5,2024.0,3042.000000,2.458333,1.291667,1.208333,77289.761905,9066.113460,70.779167,50.587500,6.962500,12.866667,1287.612963,0.00000
Albert Park,18858.0,2024.0,3206.000000,2.225806,1.451613,0.516129,138784.000000,18004.743688,0.583871,1.361290,4.548387,8.516129,663.440860,0.00000
Alexandra,20412.5,2024.0,3712.750000,1.500000,1.000000,2.000000,52332.180952,6947.566013,2.375000,3.550000,96.350000,86.025000,433.500000,0.25000
Alfredton,19570.5,2024.0,3350.047619,3.500000,1.833333,2.023810,71850.457143,18035.230371,1.461905,2.823810,100.023810,74.502381,558.247619,0.97619
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Yarram,21187.0,2024.0,3971.000000,2.000000,2.000000,1.000000,70855.019048,5530.180592,7.300000,8.800000,163.100000,125.900000,341.500000,1.00000
Yarraville,11951.5,2024.0,3013.000000,2.500000,1.333333,1.125000,96937.295238,17743.666356,0.787500,1.808333,1.236111,2.570833,1709.119676,0.00000
Yarrawonga,20438.0,2024.0,3730.000000,3.120000,1.640000,1.880000,58454.009524,9026.509334,59.552000,42.296000,250.668000,166.504000,7168.095333,1.00000
Yarriambiack,19758.5,2024.0,3393.000000,2.250000,0.750000,1.250000,23612.761905,6274.369491,1.250000,2.500000,308.725000,213.525000,618.466667,0.50000
Yea,20415.5,2024.0,3717.000000,1.500000,0.500000,1.500000,55994.266667,4046.400489,6.350000,6.650000,56.450000,54.700000,1255.550000,1.00000

In [17]:
#a = property_data_2023_2025.loc['Abbotsford']